documentation:
  - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '*.md'
      - 'mkdocs.yml'

cli:
  - changed-files:
    - any-glob-to-any-file: 'cli/**/*'

terraform:
  - changed-files:
    - any-glob-to-any-file: 'terraform/**/*'

kubernetes:
  - changed-files:
    - any-glob-to-any-file: 'kubernetes/**/*'

docker:
  - changed-files:
    - any-glob-to-any-file:
      - 'docker-compose/**/*'
      - '**/Dockerfile'
      - '**/compose.yaml'

ansible:
  - changed-files:
    - any-glob-to-any-file: 'ansible/**/*'

github-actions:
  - changed-files:
    - any-glob-to-any-file:
      - '.github/**/*'
      - 'github-actions/**/*'

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - 'requirements.txt'
      - 'package.json'

scripts:
  - changed-files:
    - any-glob-to-any-file: 'scripts/**/*'

snippets:
  - changed-files:
    - any-glob-to-any-file: 'snippets/**/*'
