version: 2.1

orbs:
  docker: circleci/docker@2.4.0
  kubernetes: circleci/kubernetes@1.3.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  build-and-push:
    executor: docker/docker
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1
      - docker/push:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          tag: $CIRCLE_SHA1

  security-scan:
    docker:
      - image: aquasec/trivy:latest
    steps:
      - checkout
      - run:
          name: Scan Docker image
          command: |
            trivy image --exit-code 1 --severity HIGH,CRITICAL \
              $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_SHA1

  deploy-to-k8s:
    executor: kubernetes/default
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Deploy to Kubernetes
          command: |
            echo $KUBECONFIG_DATA | base64 -d > /tmp/kubeconfig
            export KUBECONFIG=/tmp/kubeconfig
            sed -i "s|IMAGE_TAG|$CIRCLE_SHA1|g" k8s/deployment.yaml
            kubectl apply -f k8s/
            kubectl rollout status deployment/app

workflows:
  build-test-deploy:
    jobs:
      - build-and-push:
          context: docker-hub
          filters:
            branches:
              only:
                - main
                - develop
      
      - security-scan:
          requires:
            - build-and-push
          filters:
            branches:
              only:
                - main
                - develop
      
      - deploy-to-k8s:
          requires:
            - security-scan
          context: kubernetes
          filters:
            branches:
              only: main