# Prometheus Operator (kube-prometheus-stack) Helm Values
fullnameOverride: prometheus

prometheus:
  prometheusSpec:
    retention: 30d
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    resources:
      requests:
        cpu: 500m
        memory: 2Gi
      limits:
        cpu: 1000m
        memory: 4Gi

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - prometheus.example.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - secretName: prometheus-tls
        hosts:
          - prometheus.example.com

grafana:
  enabled: true
  adminPassword: changeme
  
  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - grafana.example.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.example.com
  
  persistence:
    enabled: true
    storageClassName: longhorn
    size: 10Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: longhorn
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

  ingress:
    enabled: true
    ingressClassName: traefik
    hosts:
      - alertmanager.example.com
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    tls:
      - secretName: alertmanager-tls
        hosts:
          - alertmanager.example.com